# ================================================
# 3. Final merge
# --------------
# Script to merge the data frame files processed 
# using subsets of the blogs, news, and twitter 
# files.  Here the "df4" files generated by 
# script #1 and #2 are merged into a single data 
# frame referred to as "df."  The counts of all 
# matching word choices are summed to ensure the
# word with the greatest count is selected.  
# ================================================


library(dplyr)

df2 <- as.data.frame(df) 

# Merge and sort the tdm2 and tdm3
df <- rbind(df2,df4) %>%
  arrange(wrd2, wrd1, wrd3) %>%
  group_by(wrd2, wrd1,wrd3) %>%
  summarise(cnt=sum(cnt))

# Remove the subset files and save
# the merged file "df.rds"
rm(df)
rm(df2,df4)
saveRDS(df, file = "df.rds")



