
# ============================================
# 5. Reduce the data set 
# ----------------------
# Script to reduce the size of the data set 
# by eliminating word ties.  For word choices
# where the word counts are the same, this script 
# arbitrarily selects the first match.  This 
# script was also applied to the individual 
# alphabetically ordered data sets generated by 
# the n# scripts.
# ============================================

library(dplyr)

rdsFile <- "a1.rds"
df <- readRDS(rdsFile) 

dfSize = dim(df)[1]
mSize = dfSize * 2
mSzHalf = mSize/2

m <- matrix(numeric(mSize),nrow=mSzHalf,ncol=2)
mRow <- 1
foundMatch <- FALSE

firstMatch <- TRUE

# Create logical vector for rows to delete
tfDel <- logical(dfSize)

for (i in 2:nrow(df)) {

  
  # Remove NAs
  if (is.na(df[i,1])) {df[i,1] <- ""} 
  if (is.na(df[i-1,1])) {df[i-1,1] <- ""}
  if (is.na(df[i,2])) {df[i,2] <- ""} 
  if (is.na(df[i-1,2])) {df[i-1,2] <- ""} 
  
  # If last wrd2 same as current wrd2, and,
  # last wrd1 same as current wrd1, 
  # set foundMatch = True,
  # store last row # in m,
  # store count of last row in m,
  # increment mRow
  
  if (df[i,1] == df[i - 1,1] & df[i,2] == df[i - 1,2]){
    
    
    # Match was initially false, so prev row is first
    if (foundMatch == FALSE) {
      if (i == 2) {
        firstMatchRow <-  1
      }
      else if (firstMatch) {
        firstMatchRow <- (mRow)
      }
      else{
        firstMatchRow <- (mRow - 1)
      }
    }
    
    # Set match true
    foundMatch <- TRUE
    
    m[mRow,1] <- as.integer(i - 1)
    m[mRow,2] <- as.integer(df[(i - 1),4])
    
    mRow <- mRow + 1
    
    
  } # end if
  
  # If foundMatch is true,
  # but no match found this time,
  # set foundMatch to false, 
  # store last row # in m,
  # store count of last row in m,
  # get the maximum count in m, 
  # get the last row # of m, 
  #   If count of df rows in m < max, 
  #   remove the row.
  # reset matrix m,
  # set mRow back to 1
  
  else if (foundMatch == TRUE) {
    foundMatch <- FALSE
    
    m[mRow,1] <- (i - 1)
    m[mRow,2] <- as.integer(df[(i - 1),4])
    
    # Find last matrix row
    maxMatrixRow <- mRow
    
    # Find max count 
    # maxFnd <- max(m[firstMatchRow:maxMatrixRow,2])
    
    # Remove all but first row w a max / dup value
    for (n in firstMatchRow + 1:maxMatrixRow){
      x <- m[n,1]
      # Mark row for deletion
      tfDel[x] <- TRUE
    } # end for
      
    mRow <- mRow + 1
    
  } # end else if
  
} # end for loop

# --------
# Final if
# --------
# if you end on a matched list, find max
if (foundMatch == TRUE){
  m[mRow,1] <- as.integer(i)
  m[mRow,2] <- as.integer(df[i,4])

  # Find last matrix row
  maxMatrixRow <- mRow
    
  # Find max count
  # maxFnd <- max(m[firstMatchRow:maxMatrixRow,2])
  
  # Remove all but first row w a max / dup value
  for (n in firstMatchRow + 1:maxMatrixRow){
    x <- m[n,1]
    # Mark row for deletion
    tfDel[x] <- TRUE
  } # end for
  
} # end final if


# Delete the rows with smaller totals
df2 <- df[!tfDel,]

# Save the reduced size data set
saveRDS(df2, rdsFile)

# rm(df,df1,df2,m,dfSize,foundMatch, maxMatrixRow, i, n, firstMatch,firstMatchRow,mRow,mSize,mSzHalf,tfDel,x)


# -------------
# End of Script
# -------------

